GPU: '0'
b1: 0.5
b2: 0.999
batch_size: 1
datasets_path: datasets/2022_0524
fmap: 16
gap_t: 75
gap_x: 75
gap_y: 75
lr: 5.0e-05
n_epochs: 10
output_dir: ./results
overlap_factor: 0.5
patch_t: 150
patch_x: 150
patch_y: 150
pth_path: ./pth/2022_0524_202501301602
scale_factor: 1
select_img_num: 100000
train_datasets_size: 2000
