GPU: '0'
b1: 0.5
b2: 0.999
batch_size: 1
datasets_path: datasets/29_4_2_4
fmap: 16
gap_t: 30
gap_x: 64
gap_y: 128
lr: 5.0e-05
n_epochs: 10
output_dir: ./results
overlap_factor: 0
patch_t: 30
patch_x: 64
patch_y: 128
pth_path: ./pth/29_4_2_4_202310260959
scale_factor: 1
select_img_num: 100000
train_datasets_size: 31
